### ISSUE TITLE
Guest mode not working, returning none

### ISSUE THREAD

**Issue by autumn-absconds** [diezo/Ensta#18]
```
from ensta import Guest

guest = Guest()
profile = guest.profile("pilarrubio")
print(profile)
if profile is not None:
    print(profile.biography)
    print(profile.follower_count)
    print(profile.following_count)
```

guest is returning **none**

`None`

**Comment by diezo** [comment]
This can happen when the profile you're trying to fetch doesn't exist or has been temporarily disabled. 

Please try to open that profile using your browser.

Also, I've made some changes to ensta so that it raises the correct exception. Please update the library: ```pip install ensta --upgrade``` and make sure you're on v4.2 or later.

Then, try to fetch the profile again and mention the exception here.

Thankyou

**Comment by autumn-absconds** [comment]
> This can happen when the profile you're trying to fetch doesn't exist or has been temporarily disabled.
> 
> Please try to open that profile using your browser.
> 
> Also, I've made some changes to ensta so that it raises the correct exception. Please update the library: `pip install ensta --upgrade` and make sure you're on v4.2 or later.
> 
> Then, try to fetch the profile again and mention the exception here.
> 
> Thankyou

sure , this week has been too busy for me , I'll check this soon and then close this issue.
