### ISSUE TITLE
User doesn't exist HELP!!!!!!!!!!

### ISSUE THREAD

**Issue by ak-47-brar** [diezo/Ensta#57]
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/instabot.py", line 4, in <module>
    host = Host(username, password)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/ensta/Host.py", line 33, in __init__
    self.load_session()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/ensta/Host.py", line 52, in load_session
    if not os.path.exists(self.file): return self.new_session()
  File "/home/codespace/.python/current/lib/python3.10/site-packages/ensta/Host.py", line 65, in new_session
    session_data: str = new_session_id(self.username, self.password, self.proxy)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/ensta/Authentication.py", line 71, in new_session_id
    if response_json.get("status", "") != "ok": raise AuthenticationError("User doesn't exist.")
ensta.lib.Exceptions.AuthenticationError: User doesn't exist.

**Comment by diezo** [comment]
have you tried using your email address instead of username?

**Comment by ak-47-brar** [comment]
yes already tried but not worked

**Comment by diezo** [comment]
i'll need more context into this issue. are you on discord? we can discuss it there: https://discord.com/invite/pU4knSwmQe

**Comment by ak-47-brar** [comment]
no man not on discord

**Comment by diezo** [comment]
@ak-47-brar if you had 2fa enabled on your account, that could be the reason.

2FA has now been implemented and you can log into your account as usual.

thanks.

**Comment by ak-47-brar** [comment]
no 2fa no enabled

**Comment by diezo** [comment]
try changing your password to a stronger one because weak password throws a checkpoint required error.

**Comment by ak-47-brar** [comment]
ok I'll try

**Comment by diezo** [comment]
i looked into this issue and turns out this could be because you're using a flagged IP address, probably deployed your app to cloud. because instagram doesn't allow requests from common cloud providers. possible solutions would be to use quality proxies. if that doesn't work either, then you have to generate session_id on your local machine and use it while initializing SessionHost class in the cloud while using proxies. i've tried webshare.io proxies and it works except for the login endpoint.
